#!/usr/bin/env python3
"""Generate bootloader_pubkey.c from deterministic dev fixture key."""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

KEY_SEED = b"stm32-bare-metal-dev-fixture"
OUT_C = Path(__file__).resolve().parent.parent / "lib" / "boot" / "src" / "boot_pubkey.c"

try:
    from ecdsa import NIST256p, SigningKey
except ImportError:
    print("Thieu ecdsa. Chay: pip install ecdsa", file=sys.stderr)
    sys.exit(1)


def derive_signing_key() -> SigningKey:
    priv = int.from_bytes(hashlib.sha256(KEY_SEED).digest(), "big") % NIST256p.order
    if priv == 0:
        priv = 1
    return SigningKey.from_secret_exponent(priv, curve=NIST256p)


def main() -> int:
    sk = derive_signing_key()
    pub = sk.get_verifying_key().to_string()

    lines = ["/* Auto-generated by tools/keygen.py — do not edit */", "#include <boot_pubkey.h>", ""]
    lines.append("const uint8_t bootloader_pubkey[64] = {")
    for i in range(0, 64, 8):
        chunk = ", ".join(f"0x{b:02X}" for b in pub[i : i + 8])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")

    OUT_C.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_C}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
